# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#f5a9ad"          # Main text color
theme[title]="#f5a9ad"            # Title color for boxes
theme[hi_fg]="#9B6E69"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#ab7679"       # Color of inactive/disabled text
theme[graph_text]="#CB666C"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]=""           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#a25156"       # Background color of selected item in processes box
theme[selected_fg]="#f5a9ad"       # Foreground color of selected item in processes box
theme[proc_misc]="#CB666C"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#9B6E69"           # Cpu box outline color
theme[mem_box]="#954377"           # Memory/disks box outline color
theme[net_box]="#9B6E69"           # Net up/down box outline color
theme[proc_box]="#954377"          # Processes box outline color
theme[div_line]="#954377"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#ab7679"          # Background color of the percentage meters
theme[used_start]="#CB666C"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#CB666C"
theme[available_start]="#D36D6B"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#D36D6B"
theme[cached_start]="#CB666C"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#CB666C"
theme[free_start]="#D36D6B"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#D36D6B"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#9B6E69"        # CPU graph colors
theme[cpu_mid]="#B15270"
theme[cpu_end]="#954377"
theme[download_start]="#CB666C"    # Download graph colors
theme[download_mid]="#954377"
theme[download_end]="#954377"  
theme[upload_start]="#B15270"     # Upload graph colors
theme[upload_mid]="#B15270"
theme[upload_end]="#D36D6B"
theme[process_start]="#CB666C"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#D36D6B"
theme[process_end]="#C15E6D"
